### ISSUE TITLE
NVCC std::tuple GPU warning

### ISSUE THREAD

**Issue by jonwong12** [LLNL/serac#485] opened 2021-06-08 01:03 UTC
a more human friendly translation of this warning:

`std::tuple`'s operator= is not marked with `__device__`, so it can't be called from a `__device__` context. 

This is confusing, because nvcc is supposed to support `std::tuple` since 9.2:
https://docs.nvidia.com/cuda/archive/9.2/cuda-toolkit-release-notes/index.html#cuda-compiler-new-features

<img width="798" alt="Screen Shot 2021-06-07 at 4 03 14 PM" src="https://user-images.githubusercontent.com/61714427/121098181-2ee41780-c7aa-11eb-92c7-d19f3bc78557.png">

My guess is that nvcc only supports the `constexpr` parts of `std::tuple` in device code, and since this copy constructor isn't `constexpr` until C++20, it won't work in device code. That being said, if we want to pursue implementing a small `serac::tuple` object, nothing would prevent us from making those constructors `constexpr` and working on GPUs.

_Originally posted by @samuelpmishLLNL in https://github.com/LLNL/serac/pull/478#discussion_r646999352_

**Comment by joshessman-llnl** [comment] 2021-06-21 12:57
I believe this is resolved by #493 as it introduces a `serac::tuple` that is more GPU-friendly.

**Comment by samuelpmishLLNL** [comment] 2021-06-21 16:08
oops, #493 was intended to just be the changes to the build system. I must have had other changes already committed when I made the branch. I'll try to revert them and make #493 more focused on just getting serac building with cuda.

**Comment by samuelpmishLLNL** [comment] 2021-06-21 16:10
the effort to move from `std::tuple` -> `serac::tuple` is still going on, but now it's taking place in feature/jonwong12/gpu_functional_comparisons. Should we make a separate PR just for the adoption of `serac::tuple`?

**Comment by jonwong12** [comment] 2021-06-21 17:43
I think it makes sense to have a separate PR just for that. It seems like a pretty big roadblock.

**Comment by joshessman-llnl** [comment] 2021-10-12 15:53
Resolved by the introduction of `serac::tuple`

**Closed as completed by joshessman-llnl** 2021-10-12 15:53 UTC
