### ISSUE TITLE
Tests fail to build: ld: error: lib/libserac_numerics.so: undefined reference to serac::BoundaryCondition::setDofs(mfem::Vector&, double) const

### ISSUE THREAD

**Issue by yurivict** [LLNL/serac#786] opened 2022-09-05 07:14 UTC
```
[ 15% 20/98] : && /usr/bin/c++ -Wall -Wextra  -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer     -Werror  -Wshadow -Wdouble-promotion -Wconversion -Wundef -Wnull-dereference -Wold-style-cast  -Wpedantic -Wno-c++2a-extensions -Wunused-private-field  -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer -fstack-protector-strong -rdynamic     -Wl,-rpath=/usr/local/lib/gcc11 -Wl,-rpath -Wl,/usr/local/lib -L/usr/local/lib/gcc11 src/serac/numerics/functional/tests/CMakeFiles/tensor_unit_tests.dir/tensor_unit_tests.cpp.o -o tests/tensor_unit_tests  -Wl,-rpath,/disk-samsung/freebsd-ports/science/serac/work/.build/lib:/usr/local/lib  lib/libgtest_main.so  lib/libgtest.so  -pthread  lib/libserac_mesh.so  lib/libserac_numerics.so  lib/libserac_infrastructure.so  /usr/local/lib/libaxom.so  /usr/local/lib/libmfem.so.4.4.0  /usr/local/lib/libHYPRE.so  /usr/local/lib/libconduit_relay_mpi_io.so  /usr/local/lib/libconduit_relay.so  -lrt  -pthread  /usr/local/lib/libhdf5.so.200.2.0  /usr/local/lib/libsiloh5.so  -lm  -ldl  /usr/local/lib/libconduit_blueprint_mpi.so  /usr/local/lib/libconduit_blueprint.so  /usr/local/lib/libconduit_relay_mpi.so  /usr/local/lib/libconduit.so  /usr/local/lib/libmpicxx.so  /usr/local/lib/libmpi.so  /usr/local/lib/liblua-5.4.so && :
FAILED: tests/tensor_unit_tests 
: && /usr/bin/c++ -Wall -Wextra  -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer     -Werror  -Wshadow -Wdouble-promotion -Wconversion -Wundef -Wnull-dereference -Wold-style-cast  -Wpedantic -Wno-c++2a-extensions -Wunused-private-field  -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer -fstack-protector-strong -rdynamic     -Wl,-rpath=/usr/local/lib/gcc11 -Wl,-rpath -Wl,/usr/local/lib -L/usr/local/lib/gcc11 src/serac/numerics/functional/tests/CMakeFiles/tensor_unit_tests.dir/tensor_unit_tests.cpp.o -o tests/tensor_unit_tests  -Wl,-rpath,/disk-samsung/freebsd-ports/science/serac/work/.build/lib:/usr/local/lib  lib/libgtest_main.so  lib/libgtest.so  -pthread  lib/libserac_mesh.so  lib/libserac_numerics.so  lib/libserac_infrastructure.so  /usr/local/lib/libaxom.so  /usr/local/lib/libmfem.so.4.4.0  /usr/local/lib/libHYPRE.so  /usr/local/lib/libconduit_relay_mpi_io.so  /usr/local/lib/libconduit_relay.so  -lrt  -pthread  /usr/local/lib/libhdf5.so.200.2.0  /usr/local/lib/libsiloh5.so  -lm  -ldl  /usr/local/lib/libconduit_blueprint_mpi.so  /usr/local/lib/libconduit_blueprint.so  /usr/local/lib/libconduit_relay_mpi.so  /usr/local/lib/libconduit.so  /usr/local/lib/libmpicxx.so  /usr/local/lib/libmpi.so  /usr/local/lib/liblua-5.4.so && :
ld: error: lib/libserac_numerics.so: undefined reference to serac::BoundaryCondition::setDofs(mfem::Vector&, double) const [--no-allow-shlib-undefined]
ld: error: lib/libserac_numerics.so: undefined reference to serac::BoundaryConditionManager::updateAllDofs() const [--no-allow-shlib-undefined]
c++: error: linker command failed with exit code 1 (use -v to see invocation)
^Cninja: build stopped: interrupted by user.
```

clang-14
FreeBSD 13.1

**Comment by samuelpmishLLNL** [comment] 2022-09-12 16:26
Thanks for the error report, I believe we're only testing with serac's targets built as static libraries right now, so there's likely a handful of issues with shared libraries. We should add shared library builds to our CI jobs to catch issues like this in the future.

**Comment by white238** [comment] 2022-09-12 16:43
Related #218

**Comment by jamiebramwell** [comment] 2022-10-24 18:13
This is a duplicate of #218

**Closed as not planned by jamiebramwell** 2022-10-24 18:13 UTC
