### ISSUE TITLE
Enable codevelop builds when using CUDA

### ISSUE THREAD

**Issue by samuelpmishLLNL** [LLNL/serac#767] opened 2022-08-15 18:02 UTC
When configuring serac with `ENABLE_CODEVELOP` on the `develop` branch, CMake emits the error:

```
...
[cmake] -- Serac Code Checks: ON
[cmake] -- Configuring done
[cmake] CMake Error: install(EXPORT "serac-targets" ...) includes target "cuda" more than once in the export set.
[cmake] -- Generating done
[cmake] CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by white238** [comment] 2022-08-15 18:04
#748

CUDA builds have not been enabled for codevelop. Referencing these together so we can fix them all at once.

**Comment by white238** [comment] 2024-01-29 21:49
duplicate of #748 which has more up to date info

**Closed as completed by white238** 2024-01-29 21:49 UTC
Labels: enhancement, build
