### ISSUE TITLE
Thermal-only input files don't work

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#401] opened 2021-02-25 00:33 UTC
Due to issues with inlet verifiers, thermal-only input files currently do not work.

**Comment by joshessman-llnl** [comment] 2021-02-25 15:12
It looks like this will be fixed by https://github.com/LLNL/axom/pull/481

**Comment by jamiebramwell** [comment] 2021-02-25 16:49
Yeah, I looked into fixing this, and decided it was worth it to just wait for this to come down the pipe and do it right.

**Comment by joshessman-llnl** [comment] 2021-03-11 18:23
Tested + confirmed to work with:

- [x] https://github.com/LLNL/axom/pull/495

**Closed as completed** 2021-06-16 18:22 UTC
Labels: bug, input
