### ISSUE TITLE
Input file: Error occurs when `thermal_conduction` block is missing

### ISSUE THREAD

**Issue by white238** [LLNL/serac#489] opened 2021-06-10 00:44 UTC
Our default values for `thermal_conduction` have created a state where we error if it is not user-defined in the input file.

Example of broken input file:

https://github.com/LLNL/serac/blob/develop/data/input_files/tests/solid/dyn_direct_solve.lua

Error:

```
[WARNING (toss_3_x86_64_ib/2021_06_09_12_52_11/builds/spack-stage-axom-0.4.0serac-vhbob7l722e4rdwzrjd5n5wgrg36zlbd/spack-src/src/axom/sidre/core/Group.cpp:123)]
Failed Check: !intpath.empty() && group->hasChildView(intpath)
[Group: 'input_file/thermal_conduction/equation_solver/linear/type'] No View with name 'value'

[ERROR (toss_3_x86_64_ib/2021_06_09_12_52_11/builds/spack-stage-axom-0.4.0serac-vhbob7l722e4rdwzrjd5n5wgrg36zlbd/spack-src/src/axom/inlet/Field.cpp:254)]
[Inlet] Field does not contain a value
** StackTrace of 14 frames **
Frame 1: axom::slic::logErrorMessage(std::string const&, std::string const&, int)
Frame 2: axom::inlet::Field::checkExistenceAndType(axom::sidre::DataTypeId) const
Frame 3: std::string axom::inlet::Field::get<std::string>() const
Frame 4: _ZNK4axom5inlet5Proxy3getISsEENSt9enable_ifIXsr6detail18is_inlet_primitiveIT_EE5valueES4_E4typeEv
Frame 5: axom::inlet::Proxy::operator std::string<std::string, void>() const
Frame 6: FromInlet<std::variant<serac::IterativeSolverOptions, serac::CustomSolverOptions, serac::DirectSolverOptions> >::operator()(axom::inlet::Container const&)
Frame 7: _ZNK4axom5inlet9Container3getISt7variantIJN5serac22IterativeSolverOptionsENS4_19CustomSolverOptionsENS4_19DirectSolverOptionsEEEEENSt9enable_ifIXaaaaaantsr6detail18is_inlet_primitiveIT_EE5valuentsr6detail14is_inlet_arrayISA_EE5valuentsr6detail13is_inlet_dictISA_EE5valuentsr6detail13is_std_vectorISA_EE5valueESA_E4typeERKSs
Frame 8: _ZNK4axom5inlet5Proxy3getISt7variantIJN5serac22IterativeSolverOptionsENS4_19CustomSolverOptionsENS4_19DirectSolverOptionsEEEEENSt9enable_ifIXaantsr6detail18is_inlet_primitiveIT_EE5valuentsr6detail15is_std_functionISA_EE5valueESA_E4typeEv
Frame 9: FromInlet<serac::ThermalConduction::InputOptions>::operator()(axom::inlet::Container const&)
Frame 10: _ZNK4axom5inlet9Container3getIN5serac17ThermalConduction12InputOptionsEEENSt9enable_ifIXaaaaaantsr6detail18is_inlet_primitiveIT_EE5valuentsr6detail14is_inlet_arrayIS7_EE5valuentsr6detail13is_inlet_dictIS7_EE5valuentsr6detail13is_std_vectorIS7_EE5valueES7_E4typeERKSs
Frame 11: _ZNK4axom5inlet5Proxy3getIN5serac17ThermalConduction12InputOptionsEEENSt9enable_ifIXaantsr6detail18is_inlet_primitiveIT_EE5valuentsr6detail15is_std_functionIS7_EE5valueES7_E4typeEv
Frame 12: main
Frame 13: __libc_start_main
Frame 14: ./bin/serac() [0x726149]
=====
```

**Comment by joshessman-llnl** [comment] 2021-06-14 14:11
Probably a duplicate of https://github.com/LLNL/serac/issues/401, trying to build the most recent version of Axom to see if it's been fixed but running into some Conduit linking issues

**Closed as completed** 2021-06-16 18:22 UTC
Labels: bug, invalid, CS, input
